name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main  # Ğ˜Ğ·Ğ¼ĞµĞ½Ğ¸ Ğ½Ğ° Ğ½ÑƒĞ¶Ğ½ÑƒÑ Ğ²ĞµÑ‚ĞºÑƒ
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‚ Check out repository
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: âœ¨ Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸ¯ Download Chrome & ChromeDriver
        uses: browsers-lambdatest/selenium-installer-action@v1
        with:
          browser-name: chrome
          version: latest-stable

      - name: ğŸ’¥ Run tests and generate Allure report
        run: |
          export CHROMEDRIVER_PATH=$(pwd)/chromedriver
          pytest --alluredir=./reports

      - name: ğŸŒ Hosting Allure report using GitHub Pages
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: dawidd6/action-allure-report@v2
        env:
          GH_PAGES_BRANCH: gh-pages
          REPORT_DIR: reports
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
